# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: write

env:
  BUILD_CONFIGURATION: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) && 'Release' || 'Debug' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["win-x64", "linux-x64", "linux-arm64", "osx-x64", "osx-arm64"]
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build -c "$BUILD_CONFIGURATION"
    - name: Publish
      run: dotnet publish -r ${{ matrix.os }} -c "$BUILD_CONFIGURATION" --self-contained
    - name: Upload build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ format('FmodRipper-{0}', matrix.os) }}
        path: ${{ format('FmodRipper/bin/{0}/net8.0/{1}/publish', env.BUILD_CONFIGURATION, matrix.os) }}
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts
      - name: Zip artifacts
        run: for i in artifacts/*/; do zip -r "${i%/}.zip" "$i"; done
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: artifacts/*.zip
